### ISSUE TITLE
Debug failing tests in Ubuntu

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxEleven#7]
The following 2 tests are disabled because they are failing in Ubuntu (ce-dev2.gluu.org):

https://github.com/GluuFederation/oxEleven/blob/master/Client/src/test/java/org/gluu/oxeleven/PKCS11RestServiceTest.java#L898

https://github.com/GluuFederation/oxEleven/blob/master/Client/src/test/java/org/gluu/oxeleven/PKCS11RestServiceTest.java#L953

The steps to install SoftHSMv2 in Ubuntu are:

```
sudo apt-get install automake -y
sudo apt-get install libssl-dev -y
sudo apt-get install libtool -y

cd /opt
git clone https://github.com/opendnssec/SoftHSMv2.git
cd SoftHSMv2
sh autogen.sh
./configure
make
sudo make install
softhsm2-util --init-token --slot 0 --label "SoftHSM"
```

**Comment by yurem** [comment]
Should we install RHEL into ce-dev to enable them?

**Comment by qbert2k** [comment]
I've also tried to install SoftSHM in CentOS (ce-dev.gluu.org) but build failed due to a missing dependency: openssl is supposed to come with libgost.so but it doesn't in CentOS.

**Comment by qbert2k** [comment]
The steps I followed to install in CentOS are:

```
yum install automake -y
yum install autoconf -y
yum install libtool -y
yum install openssl -y
yum install openssl-devel -y

cd /opt
git clone https://github.com/opendnssec/SoftHSMv2.git
cd SoftHSMv2
sh autogen.sh
./configure
```

At this point ./configure is failing because the missing GOST because cannot find the file:
```
/usr/lib64/openssl/engines/libgost.so
```

**Comment by yurem** [comment]
@qbert2k, @nynymike  if we need to include SoftHSMv2 into other CE dists we need to not install it manually, we need to open issue in setup project and assing it to Adrian. I think we need to build ready to use package instead of compiling it in CE VM. Also after installing development packages with headers dependencies into CE rpm/deb will be huge. I offer to do next:

1. Build rpm/deb for SoftHSMv2 
2. Install result package into CE chroot as generic package.
3. Package CE as before.

**Comment by qbert2k** [comment]
The problem was with OpenJDK because it does not support SunEC provider.
Now oxEleven is using the BC provider and all tests success including ES512 algorithm.
